-- =====================================================================
-- CREATE TEST APPLICATION
-- Run this AFTER FIX_EVERYTHING.sql to create a test application
-- =====================================================================

INSERT INTO medical_applications (
    application_number,
    status,
    employee_name,
    employee_id,
    designation,
    department,
    cghs_card_number,
    cghs_dispensary,
    card_validity,
    ward_entitlement,
    patient_name,
    patient_cghs_card,
    relationship_with_employee,
    hospital_name,
    hospital_address,
    treatment_type,
    clothes_provided,
    prior_permission,
    emergency_treatment,
    health_insurance,
    total_amount_claimed,
    approved_amount,
    bank_name,
    branch_address,
    account_number,
    ifsc_code,
    enclosures_count,
    photocopy_cghs_card,
    photocopies_original_prescriptions,
    original_bills,
    signature,
    declaration_place,
    declaration_date,
    faculty_employee_id,
    mobile_number,
    email,
    submitted_at,
    updated_at
) VALUES (
    'TEST-2025-0001',
    'pending',
    'Dr. Rajesh Kumar',
    'EMP001',
    'Assistant Professor',
    'Computer Science',
    'CGHS123456',
    'JNU Dispensary',
    NOW() + INTERVAL '1 year',
    'General',
    'Dr. Rajesh Kumar',
    'CGHS123456',
    'Self',
    'AIIMS Hospital',
    'Ansari Nagar, New Delhi',
    'opd',
    false,
    false,
    false,
    false,
    5000.00,
    0.00,
    'State Bank of India',
    'JNU Branch, New Delhi',
    '1234567890',
    'SBIN0001234',
    3,
    true,
    true,
    true,
    'Dr. Rajesh Kumar',
    'New Delhi',
    NOW(),
    'FAC001',
    '9876543210',
    'rajesh@jnu.ac.in',
    NOW(),
    NOW()
) RETURNING id, application_number, status;

-- Show what was created
SELECT 
    '✅ Test application created!' as message,
    id,
    application_number,
    status,
    employee_name,
    total_amount_claimed
FROM medical_applications
WHERE application_number = 'TEST-2025-0001';
